DROP TABLE IF EXISTS venues;

CREATE TABLE venues(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR DEFAULT NULL,
    image VARCHAR DEFAULT NULL,
    address VARCHAR DEFAULT NULL,
    user_id INTEGER REFERENCES users(id) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);